#!/bin/bash

docker run -it --rm \
    --user "$(id -u):$(id -g)" \
    --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
    --mount type=bind,source="$(pwd)",target=/app \
    vibecc:latest \
    "$@"
